Configs:
  explosion-protection-all: true
  allow-admin-snoop: true
  allow-admin-break: ture
  quick-protect:
    enable: true
    item: 'STICK'
  protocollib-name-overide:
    enable: true
    use_users_name: true
  enable-hopper-blocking: true